export interface Notification {
  id: number;
  userId: number;
  type: NotificationType;
  message: string;
  isRead: boolean;
  createdAt: string;
  relatedEntityId?: number;
}

export enum NotificationType {
  // Admin notifications
  CUSTOMER_REGISTERED = 'CUSTOMER_REGISTERED',
  CUSTOMER_MILESTONE = 'CUSTOMER_MILESTONE',
  APPOINTMENT_BOOKED = 'APPOINTMENT_BOOKED',
  APPOINTMENT_EDITED = 'APPOINTMENT_EDITED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  GALLERY_PHOTO_LIKED = 'GALLERY_PHOTO_LIKED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  
  // Customer notifications
  APPOINTMENT_APPROVED = 'APPOINTMENT_APPROVED',
  APPOINTMENT_DECLINED = 'APPOINTMENT_DECLINED',
  APPOINTMENT_STATUS_CHANGED = 'APPOINTMENT_STATUS_CHANGED',
  JACKET_READY = 'JACKET_READY',
  PAYMENT_REMINDER = 'PAYMENT_REMINDER',
  GALLERY_PHOTO_UPLOADED = 'GALLERY_PHOTO_UPLOADED',
  BILL_UPLOADED = 'BILL_UPLOADED'
}
